# create the folder structure
mkdir -p .github/workflows

name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Make test script executable
        run: chmod +x t/run_tests
      - name: Run tests
        run: ./t/run_tests
'@ | Out-File -FilePath .github/workflows/test.yml -Encoding UTF8

# create a basic gitignore
echo "git-filter-repo/" > .gitignore
